---

- name: Deploy Portainer components
  hosts: docker01
  become: true
  tasks:
    - name: install dependencies
      pip:
        name:
          - jsondiff
          - pyyaml
        state: present
    - name: deploy 'Wordpress' Stack
      docker_stack:
        state: present
        name: Wordpress
        compose:
          - version: '3'
            services:
               db:
                 image: mysql:latest
                 volumes:
                   - db_data:/var/lib/mysql
                 restart: always
                 environment:
                   MYSQL_ROOT_PASSWORD: NotSecureAtAll!
                   MYSQL_DATABASE: wordpress
                   MYSQL_USER: wordpress
                   MYSQL_PASSWORD: AbsolutelyNotSecure!
               wordpress:
                 image: wordpress:latest
                 ports:
                   - 80
                 restart: always
                 environment:
                   WORDPRESS_DB_HOST: db:3306
                   WORDPRESS_DB_USER: wordpress
                   WORDPRESS_DB_PASSWORD: AbsolutelyNotSecure!
            volumes:
                db_data:
